Feat/lsp8 compatibility (create, mint, transfer)
lukso-network/universalprofile-test-dapp pull request #86
Opened 2022-11-22 15:27 UTC by samuel-videau

2022-11-22 16:05 UTC, Hugoo commented on src/components/endpoints/Mint.vue
> +            console.log(JSON.stringify(payload, null, 2))
no need to stringify / format the receipt?

2022-11-22 16:06 UTC, Hugoo commented on src/components/endpoints/Transfer.vue
> +  if (tokenType.value === 'LSP7') {
you could reuse the enum here

2022-11-22 16:30 UTC, dzbo requested changes
Also test would be welcome, not big deal in test dApp tho but I guess it would be cool for learning purpose.

2022-11-22 16:30 UTC, dzbo commented on src/components/endpoints/Mint.vue
> +        <div class="field">
Rather then duplicating I would move this form into own component so it can be shared in Asses and Mint

2022-11-22 16:30 UTC, dzbo commented on src/components/endpoints/Transfer.vue
> +        <label class="label">Token id (!: only bytes32, no uint256)</label>
Instead of the value comment in label I would rather add example in input placeholder.

2022-11-22 22:29 UTC, samuel-videau commented
> Also test would be welcome, not big deal in test dApp tho but I guess it would be cool for learning purpose.

I'll keep that for later, just created that so now I can test efficiently my intergrations on the browser extension

2022-11-23 08:42 UTC, dzbo commented on src/components/endpoints/Assets.vue
> +      </div>
We repeat this dropdown 3 times, should be in component

2022-11-23 08:42 UTC, dzbo commented on src/components/endpoints/Transfer.vue
> +        <label class="label">Token id (!: only bytes32, no uint256)</label>
?

2022-11-23 08:42 UTC, dzbo commented on src/components/endpoints/Assets.vue
> +  type: 'LSP7',
Why it was resolved? still not using enum that was added to `types` file. Btw, only comment creators should resolve them.

2022-11-23 08:59 UTC, dzbo commented
@samuel-videau let's also make sure everything is lined with ClickUp ticket, if there isn't any feel free to create one. 

https://app.clickup.com/t/33v8f9w

2022-11-23 10:37 UTC, dzbo approved these changes

2022-11-24 15:33 UTC, merged